import { createFileRoute, Link } from "@tanstack/react-router";
import { HomeLayout } from "fumadocs-ui/layouts/home";
import { baseOptions } from "../lib/layout.shared";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  return (
    <HomeLayout {...baseOptions()}>
      <div className="flex flex-col items-start flex-1 px-16 py-8">
        <h1 className="font-bold text-5xl mb-4">
          Gaming<span className="text-fd-primary">TS</span>
        </h1>
        <p className="text-lg text-fd-muted-foreground mb-6">
          A TypeScript Extension for writing Genius Invokation TCG cards.
        </p>
        <div className="flex flex-row gap-4 mb-6">
          <Link
            to="/docs/$"
            params={{
              _splat: "user-guide",
            }}
            className="px-3 py-2 rounded-lg bg-fd-primary text-fd-primary-foreground font-medium text-sm"
          >
            User Guide
          </Link>
          <Link
            to="/docs/$"
            params={{
              _splat: "runtime-guide",
            }}
            className="px-3 py-2 rounded-lg bg-fd-secondary text-fd-secondary-foreground font-medium text-sm"
          >
            Runtime Author Guide
          </Link>
          <Link
            to="/docs/$"
            params={{
              _splat: "internal",
            }}
            className="px-3 py-2 rounded-lg bg-fd-secondary text-fd-secondary-foreground font-medium text-sm"
          >
            Developer Guide
          </Link>
        </div>
        <p className="text-red-500 text-3xl my-3">
          All documents under this site are generated by AI and may be INCORRECT
          and OUTDATED. Read with caution.
        </p>
      </div>
    </HomeLayout>
  );
}
