packages:
  - 'packages/*'
  - 'examples/*'
  - 'docs'

allowBuilds:
  esbuild: true
  keytar: true

autoInstallPeers: false

nodeLinker: hoisted

minimumReleaseAgeExclude:
  - '@gi-tcg/*'
  - espolar

catalog:
  typescript: npm:@typescript/typescript6@^6.0.1

# patchedDependencies:
#   ajv@8.20.0: patches/ajv@8.20.0.patch
