packages:
  - 'packages/*'
  - 'examples/*'
  - 'docs'

allowBuilds:
  esbuild: true
  keytar: true

autoInstallPeers: false

nodeLinker: hoisted

minimumReleaseAgeExclude:
  - '@gi-tcg/*'
  - espolar

catalog:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2

overrides:
  typescript: npm:typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2

patchedDependencies:
  '@volar/typescript': patches/@volar__typescript.patch
  'nitro@3.0.260429-beta': patches/nitro@3.0.260429-beta.patch
  'typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2': patches/typescript-native-bridge@6.0.3-bridge.16.tsgo.7.0.2.patch

# patchedDependencies:
#   ajv@8.20.0: patches/ajv@8.20.0.patch
