packages:
  - 'packages/*'
  - 'examples/*'
  - 'docs'

allowBuilds:
  esbuild: true
  keytar: true

autoInstallPeers: false

nodeLinker: hoisted
injectWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@gi-tcg/*'
  - espolar

catalog:
  typescript: ^5.9.3
