import __gts_query from '@example/provider/query';
import __gts_root_vm from '@example/provider/vm';

namespace __gts_util { export type UniqueKeyProbSegment = "__gts_unique_prob_seg__"; export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never; };

/**
 * @id 112011
 * @name 歌声之环
 * @description
 * 结束阶段：治疗所有我方角色1点，然后对我方出战角色附着水元素。
 * 可用次数：2
 */
export const MelodyLoop: gts_binding_type_2 = 0 as any;

/**
 * @id 12012
 * @name 演唱，开始♪
 * @description
 * 造成1点水元素伤害，召唤歌声之环。
 */
const WhisperOfWater: gts_binding_type_1 = 0 as any;

/**
 * @id 1201
 * @name 芭芭拉
 * @description
 * 无论何时都能治愈人心。
 */
export const Barbara: gts_binding_type_0 = 0 as any;

import { A } from "./test2.gts";

export const add = (a: number, b: number) => {
  return a + b;
};

type __gts_meta = '~meta';

const __gts_meta: __gts_meta = 0 as any;

type __gts_Action = '~action';

const __gts_Action: __gts_Action = 0 as any;

type __gts_namedDef = '~namedDefinition';

const __gts_namedDef: __gts_namedDef = 0 as any;

type __gts_Prelude = '~prelude';

const __gts_Prelude: __gts_Prelude = 0 as any;

type __gts_rootVmDefType_0 = (typeof __gts_root_vm)[__gts_namedDef]; type __gts_rootVmInitMetaType_1 = __gts_rootVmDefType_0[__gts_meta];;
type __gts_attr_obj_3_uniqueKey_lhs = { [__gts_meta]: __gts_rootVmInitMetaType_1;  uniqueKey: __gts_rootVmDefType_0 extends { ["character"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_3_uniqueKey_lhs!: __gts_attr_obj_3_uniqueKey_lhs; let __gts_attr_obj_3_uniqueKey = __gts_attr_obj_3_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_3_uniqueKey = typeof __gts_attr_obj_3_uniqueKey; let __gts_attr_obj_3_uniqueKeyFor___gts_attr_obj_3!: `${__gts_attr_obj_3_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_3`; interface __gts_rootVmDefType_0_uniqueKeyProbeHelper { [__gts_attr_obj_3_uniqueKeyFor___gts_attr_obj_3]: 1; } type __gts_attr_obj_3_omittedKeys = __gts_meta | ( __gts_attr_obj_3_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_rootVmDefType_0_uniqueKeyProbeHelper ? keyof __gts_rootVmDefType_0                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_rootVmDefType_0_uniqueKeyProbeHelper & `${__gts_attr_obj_3_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "character"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_3!: { [__gts_meta]: __gts_rootVmInitMetaType_1 } & Omit<__gts_rootVmDefType_0, __gts_attr_obj_3_omittedKeys>;;

const __gts_attrRet_4 = __gts_attr_obj_3.character();

type __gts_nestedVm_5 = __gts_attrRet_4 extends { namedDefinition: infer Def } ? Def : { [__gts_meta]: unknown }; type __gts_nestedVmInitMetaType_6 = __gts_nestedVm_5[__gts_meta];;
type __gts_attr_obj_8_uniqueKey_lhs = { [__gts_meta]: __gts_nestedVmInitMetaType_6;  uniqueKey: __gts_nestedVm_5 extends { ["id"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_8_uniqueKey_lhs!: __gts_attr_obj_8_uniqueKey_lhs; let __gts_attr_obj_8_uniqueKey = __gts_attr_obj_8_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_8_uniqueKey = typeof __gts_attr_obj_8_uniqueKey; let __gts_attr_obj_8_uniqueKeyFor___gts_attr_obj_8!: `${__gts_attr_obj_8_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_8`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_8_uniqueKeyFor___gts_attr_obj_8]: 1; } type __gts_attr_obj_8_omittedKeys = __gts_meta | ( __gts_attr_obj_8_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_8_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "id"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_8!: { [__gts_meta]: __gts_nestedVmInitMetaType_6 } & Omit<__gts_nestedVm_5, __gts_attr_obj_8_omittedKeys>;;

const __gts_attrRet_9 = __gts_attr_obj_8.id(1201);

type gts_binding_type_0_lhs = { [__gts_meta]: __gts_nestedVmFinalMetaType_7; as: __gts_nestedVm_5 extends { ["id"]: { as: infer As } } ? As : unknown; }; let gts_binding_type_0_lhs!: gts_binding_type_0_lhs; let gts_binding_type_0 = gts_binding_type_0_lhs.as(); type gts_binding_type_0 = typeof gts_binding_type_0;;
type __gts_attrRet_9 = typeof __gts_attrRet_9; type __gts_newMeta__10 = __gts_attrRet_9 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_nestedVmInitMetaType_6;
type __gts_attr_obj_11_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__10;  uniqueKey: __gts_nestedVm_5 extends { ["since"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_11_uniqueKey_lhs!: __gts_attr_obj_11_uniqueKey_lhs; let __gts_attr_obj_11_uniqueKey = __gts_attr_obj_11_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_11_uniqueKey = typeof __gts_attr_obj_11_uniqueKey; let __gts_attr_obj_11_uniqueKeyFor___gts_attr_obj_11!: `${__gts_attr_obj_11_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_11`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_11_uniqueKeyFor___gts_attr_obj_11]: 1; } type __gts_attr_obj_11_omittedKeys = __gts_meta | ( __gts_attr_obj_11_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_11_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "since"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_11!: { [__gts_meta]: __gts_newMeta__10 } & Omit<__gts_nestedVm_5, __gts_attr_obj_11_omittedKeys>;;

const __gts_attrRet_12 = __gts_attr_obj_11.since("v3.3.0");

type __gts_attrRet_12 = typeof __gts_attrRet_12; type __gts_newMeta__13 = __gts_attrRet_12 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__10;
type __gts_attr_obj_14_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__13;  uniqueKey: __gts_nestedVm_5 extends { ["tags"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_14_uniqueKey_lhs!: __gts_attr_obj_14_uniqueKey_lhs; let __gts_attr_obj_14_uniqueKey = __gts_attr_obj_14_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_14_uniqueKey = typeof __gts_attr_obj_14_uniqueKey; let __gts_attr_obj_14_uniqueKeyFor___gts_attr_obj_14!: `${__gts_attr_obj_14_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_14`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_14_uniqueKeyFor___gts_attr_obj_14]: 1; } type __gts_attr_obj_14_omittedKeys = __gts_meta | ( __gts_attr_obj_14_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_14_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "tags"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_14!: { [__gts_meta]: __gts_newMeta__13 } & Omit<__gts_nestedVm_5, __gts_attr_obj_14_omittedKeys>;;

const __gts_attrRet_15 = __gts_attr_obj_14.tags('hydro', 'catalyst', 'mondstadt');

type __gts_attrRet_15 = typeof __gts_attrRet_15; type __gts_newMeta__16 = __gts_attrRet_15 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__13;
type __gts_attr_obj_17_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__16;  uniqueKey: __gts_nestedVm_5 extends { ["health"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_17_uniqueKey_lhs!: __gts_attr_obj_17_uniqueKey_lhs; let __gts_attr_obj_17_uniqueKey = __gts_attr_obj_17_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_17_uniqueKey = typeof __gts_attr_obj_17_uniqueKey; let __gts_attr_obj_17_uniqueKeyFor___gts_attr_obj_17!: `${__gts_attr_obj_17_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_17`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_17_uniqueKeyFor___gts_attr_obj_17]: 1; } type __gts_attr_obj_17_omittedKeys = __gts_meta | ( __gts_attr_obj_17_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_17_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "health"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_17!: { [__gts_meta]: __gts_newMeta__16 } & Omit<__gts_nestedVm_5, __gts_attr_obj_17_omittedKeys>;;

const __gts_attrRet_18 = __gts_attr_obj_17.health(10);

type __gts_attrRet_18 = typeof __gts_attrRet_18; type __gts_newMeta__19 = __gts_attrRet_18 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__16;
type __gts_attr_obj_20_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__19;  uniqueKey: __gts_nestedVm_5 extends { ["energy"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_20_uniqueKey_lhs!: __gts_attr_obj_20_uniqueKey_lhs; let __gts_attr_obj_20_uniqueKey = __gts_attr_obj_20_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_20_uniqueKey = typeof __gts_attr_obj_20_uniqueKey; let __gts_attr_obj_20_uniqueKeyFor___gts_attr_obj_20!: `${__gts_attr_obj_20_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_20`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_20_uniqueKeyFor___gts_attr_obj_20]: 1; } type __gts_attr_obj_20_omittedKeys = __gts_meta | ( __gts_attr_obj_20_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_20_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "energy"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_20!: { [__gts_meta]: __gts_newMeta__19 } & Omit<__gts_nestedVm_5, __gts_attr_obj_20_omittedKeys>;;

const __gts_attrRet_21 = __gts_attr_obj_20.energy(3);

type __gts_attrRet_21 = typeof __gts_attrRet_21; type __gts_newMeta__22 = __gts_attrRet_21 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__19;
type __gts_attr_obj_23_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__22;  uniqueKey: __gts_nestedVm_5 extends { ["skills"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_23_uniqueKey_lhs!: __gts_attr_obj_23_uniqueKey_lhs; let __gts_attr_obj_23_uniqueKey = __gts_attr_obj_23_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_23_uniqueKey = typeof __gts_attr_obj_23_uniqueKey; let __gts_attr_obj_23_uniqueKeyFor___gts_attr_obj_23!: `${__gts_attr_obj_23_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_23`; interface __gts_nestedVm_5_uniqueKeyProbeHelper { [__gts_attr_obj_23_uniqueKeyFor___gts_attr_obj_23]: 1; } type __gts_attr_obj_23_omittedKeys = __gts_meta | ( __gts_attr_obj_23_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_5_uniqueKeyProbeHelper ? keyof __gts_nestedVm_5                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_5_uniqueKeyProbeHelper & `${__gts_attr_obj_23_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "skills"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_23!: { [__gts_meta]: __gts_newMeta__22 } & Omit<__gts_nestedVm_5, __gts_attr_obj_23_omittedKeys>;;

const __gts_attrRet_24 = __gts_attr_obj_23.skills(WhisperOfWater);

type __gts_attrRet_24 = typeof __gts_attrRet_24; type __gts_newMeta__25 = __gts_attrRet_24 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__22;
type __gts_nestedVmFinalMetaType_7 = __gts_newMeta__25; let __gts_nestedVmFinalMetaType_7_lhs!: { [__gts_meta]: __gts_newMeta__25 } & Omit<__gts_nestedVm_5, __gts_meta>; type __gts_nestedVmFinalMetaType_7_lhs = typeof __gts_nestedVmFinalMetaType_7_lhs; namespace __gts_nestedVmFinalMetaType_7_rans { export type Collected = "id" | "since" | "tags" | "health" | "energy" | "skills"; export type Expected = { [K in keyof __gts_nestedVm_5]: __gts_nestedVmFinalMetaType_7_lhs[K] extends { required(this: __gts_nestedVmFinalMetaType_7_lhs): true } ? K : never }[keyof __gts_nestedVm_5]; }; ((_: __gts_nestedVmFinalMetaType_7_rans.Expected extends __gts_nestedVmFinalMetaType_7_rans.Collected ? string : __gts_nestedVmFinalMetaType_7_rans.Expected) => 0)("__gts_nestedVmFinalMetaType_7_rans_NeedleString" as any as "required attributes are missing");;
type __gts_attrRet_4 = typeof __gts_attrRet_4; type __gts_newMeta__26 = __gts_attrRet_4 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_rootVmInitMetaType_1;
type __gts_rootVmFinalMetaType_2 = __gts_newMeta__26; let __gts_rootVmFinalMetaType_2_lhs!: { [__gts_meta]: __gts_newMeta__26 } & Omit<__gts_rootVmDefType_0, __gts_meta>; type __gts_rootVmFinalMetaType_2_lhs = typeof __gts_rootVmFinalMetaType_2_lhs; namespace __gts_rootVmFinalMetaType_2_rans { export type Collected = "character"; export type Expected = { [K in keyof __gts_rootVmDefType_0]: __gts_rootVmFinalMetaType_2_lhs[K] extends { required(this: __gts_rootVmFinalMetaType_2_lhs): true } ? K : never }[keyof __gts_rootVmDefType_0]; }; ((_: __gts_rootVmFinalMetaType_2_rans.Expected extends __gts_rootVmFinalMetaType_2_rans.Collected ? string : __gts_rootVmFinalMetaType_2_rans.Expected) => 0)("__gts_rootVmFinalMetaType_2_rans_NeedleString" as any as "required attributes are missing");;
type __gts_rootVmDefType_27 = (typeof __gts_root_vm)[__gts_namedDef]; type __gts_rootVmInitMetaType_28 = __gts_rootVmDefType_27[__gts_meta];;
type __gts_attr_obj_30_uniqueKey_lhs = { [__gts_meta]: __gts_rootVmInitMetaType_28;  uniqueKey: __gts_rootVmDefType_27 extends { ["skill"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_30_uniqueKey_lhs!: __gts_attr_obj_30_uniqueKey_lhs; let __gts_attr_obj_30_uniqueKey = __gts_attr_obj_30_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_30_uniqueKey = typeof __gts_attr_obj_30_uniqueKey; let __gts_attr_obj_30_uniqueKeyFor___gts_attr_obj_30!: `${__gts_attr_obj_30_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_30`; interface __gts_rootVmDefType_27_uniqueKeyProbeHelper { [__gts_attr_obj_30_uniqueKeyFor___gts_attr_obj_30]: 1; } type __gts_attr_obj_30_omittedKeys = __gts_meta | ( __gts_attr_obj_30_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_rootVmDefType_27_uniqueKeyProbeHelper ? keyof __gts_rootVmDefType_27                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_rootVmDefType_27_uniqueKeyProbeHelper & `${__gts_attr_obj_30_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "skill"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_30!: { [__gts_meta]: __gts_rootVmInitMetaType_28 } & Omit<__gts_rootVmDefType_27, __gts_attr_obj_30_omittedKeys>;;

const __gts_attrRet_31 = __gts_attr_obj_30.skill();

type __gts_nestedVm_32 = __gts_attrRet_31 extends { namedDefinition: infer Def } ? Def : { [__gts_meta]: unknown }; type __gts_nestedVmInitMetaType_33 = __gts_nestedVm_32[__gts_meta];;
type __gts_attr_obj_35_uniqueKey_lhs = { [__gts_meta]: __gts_nestedVmInitMetaType_33;  uniqueKey: __gts_nestedVm_32 extends { ["id"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_35_uniqueKey_lhs!: __gts_attr_obj_35_uniqueKey_lhs; let __gts_attr_obj_35_uniqueKey = __gts_attr_obj_35_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_35_uniqueKey = typeof __gts_attr_obj_35_uniqueKey; let __gts_attr_obj_35_uniqueKeyFor___gts_attr_obj_35!: `${__gts_attr_obj_35_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_35`; interface __gts_nestedVm_32_uniqueKeyProbeHelper { [__gts_attr_obj_35_uniqueKeyFor___gts_attr_obj_35]: 1; } type __gts_attr_obj_35_omittedKeys = __gts_meta | ( __gts_attr_obj_35_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_32_uniqueKeyProbeHelper ? keyof __gts_nestedVm_32                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_32_uniqueKeyProbeHelper & `${__gts_attr_obj_35_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "id"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_35!: { [__gts_meta]: __gts_nestedVmInitMetaType_33 } & Omit<__gts_nestedVm_32, __gts_attr_obj_35_omittedKeys>;;

const __gts_attrRet_36 = __gts_attr_obj_35.id(12011);

type gts_binding_type_1_lhs = { [__gts_meta]: __gts_nestedVmFinalMetaType_34; as: __gts_nestedVm_32 extends { ["id"]: { as: infer As } } ? As : unknown; }; let gts_binding_type_1_lhs!: gts_binding_type_1_lhs; let gts_binding_type_1 = gts_binding_type_1_lhs.as(); type gts_binding_type_1 = typeof gts_binding_type_1;;
type __gts_attrRet_36 = typeof __gts_attrRet_36; type __gts_newMeta__37 = __gts_attrRet_36 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_nestedVmInitMetaType_33;
type __gts_attr_obj_38_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__37;  uniqueKey: __gts_nestedVm_32 extends { ["cost"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_38_uniqueKey_lhs!: __gts_attr_obj_38_uniqueKey_lhs; let __gts_attr_obj_38_uniqueKey = __gts_attr_obj_38_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_38_uniqueKey = typeof __gts_attr_obj_38_uniqueKey; let __gts_attr_obj_38_uniqueKeyFor___gts_attr_obj_38!: `${__gts_attr_obj_38_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_38`; interface __gts_nestedVm_32_uniqueKeyProbeHelper { [__gts_attr_obj_38_uniqueKeyFor___gts_attr_obj_38]: 1; } type __gts_attr_obj_38_omittedKeys = __gts_meta | ( __gts_attr_obj_38_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_32_uniqueKeyProbeHelper ? keyof __gts_nestedVm_32                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_32_uniqueKeyProbeHelper & `${__gts_attr_obj_38_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "cost"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_38!: { [__gts_meta]: __gts_newMeta__37 } & Omit<__gts_nestedVm_32, __gts_attr_obj_38_omittedKeys>;;

const __gts_attrRet_39 = __gts_attr_obj_38.cost('hydro', 3);

type __gts_attrRet_39 = typeof __gts_attrRet_39; type __gts_newMeta__40 = __gts_attrRet_39 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__37;
type __gts_attr_obj_41_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__40;  uniqueKey: __gts_nestedVm_32 extends { ["variable"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_41_uniqueKey_lhs!: __gts_attr_obj_41_uniqueKey_lhs; let __gts_attr_obj_41_uniqueKey = __gts_attr_obj_41_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_41_uniqueKey = typeof __gts_attr_obj_41_uniqueKey; let __gts_attr_obj_41_uniqueKeyFor___gts_attr_obj_41!: `${__gts_attr_obj_41_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_41`; interface __gts_nestedVm_32_uniqueKeyProbeHelper { [__gts_attr_obj_41_uniqueKeyFor___gts_attr_obj_41]: 1; } type __gts_attr_obj_41_omittedKeys = __gts_meta | ( __gts_attr_obj_41_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_32_uniqueKeyProbeHelper ? keyof __gts_nestedVm_32                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_32_uniqueKeyProbeHelper & `${__gts_attr_obj_41_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "variable"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_41!: { [__gts_meta]: __gts_newMeta__40 } & Omit<__gts_nestedVm_32, __gts_attr_obj_41_omittedKeys>;;

const __gts_attrRet_42 = __gts_attr_obj_41.variable('foo', 42);

type __gts_attrRet_42 = typeof __gts_attrRet_42; type __gts_newMeta__43 = __gts_attrRet_42 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__40;
type __gts_attr_obj_44_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__43;  uniqueKey: __gts_nestedVm_32 extends { [__gts_Action]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_44_uniqueKey_lhs!: __gts_attr_obj_44_uniqueKey_lhs; let __gts_attr_obj_44_uniqueKey = __gts_attr_obj_44_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_44_uniqueKey = typeof __gts_attr_obj_44_uniqueKey; let __gts_attr_obj_44_uniqueKeyFor___gts_attr_obj_44!: `${__gts_attr_obj_44_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_44`; interface __gts_nestedVm_32_uniqueKeyProbeHelper { [__gts_attr_obj_44_uniqueKeyFor___gts_attr_obj_44]: 1; } type __gts_attr_obj_44_omittedKeys = __gts_meta | ( __gts_attr_obj_44_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_32_uniqueKeyProbeHelper ? keyof __gts_nestedVm_32                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_32_uniqueKeyProbeHelper & `${__gts_attr_obj_44_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? __gts_Action                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_44!: { [__gts_meta]: __gts_newMeta__43 } & Omit<__gts_nestedVm_32, __gts_attr_obj_44_omittedKeys>;;

const __gts_attrRet_45 = __gts_attr_obj_44[__gts_Action]((
  __gts_fnArg,
  { cryo, hydro, pyro, electro, anemo, geo, dendro, omni } = __gts_fnArg[__gts_Prelude]
) => {
  const a = __gts_fnArg.getVariable("foo");

  __gts_fnArg.damage(hydro, 1);
  __gts_fnArg.summon(MelodyLoop);
});

type __gts_nestedVmFinalMetaType_34 = __gts_newMeta__43; let __gts_nestedVmFinalMetaType_34_lhs!: { [__gts_meta]: __gts_newMeta__43 } & Omit<__gts_nestedVm_32, __gts_meta>; type __gts_nestedVmFinalMetaType_34_lhs = typeof __gts_nestedVmFinalMetaType_34_lhs; namespace __gts_nestedVmFinalMetaType_34_rans { export type Collected = "id" | "cost" | "variable" | __gts_Action; export type Expected = { [K in keyof __gts_nestedVm_32]: __gts_nestedVmFinalMetaType_34_lhs[K] extends { required(this: __gts_nestedVmFinalMetaType_34_lhs): true } ? K : never }[keyof __gts_nestedVm_32]; }; ((_: __gts_nestedVmFinalMetaType_34_rans.Expected extends __gts_nestedVmFinalMetaType_34_rans.Collected ? string : __gts_nestedVmFinalMetaType_34_rans.Expected) => 0)("__gts_nestedVmFinalMetaType_34_rans_NeedleString" as any as "required attributes are missing");;
type __gts_attrRet_31 = typeof __gts_attrRet_31; type __gts_newMeta__46 = __gts_attrRet_31 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_rootVmInitMetaType_28;
type __gts_rootVmFinalMetaType_29 = __gts_newMeta__46; let __gts_rootVmFinalMetaType_29_lhs!: { [__gts_meta]: __gts_newMeta__46 } & Omit<__gts_rootVmDefType_27, __gts_meta>; type __gts_rootVmFinalMetaType_29_lhs = typeof __gts_rootVmFinalMetaType_29_lhs; namespace __gts_rootVmFinalMetaType_29_rans { export type Collected = "skill"; export type Expected = { [K in keyof __gts_rootVmDefType_27]: __gts_rootVmFinalMetaType_29_lhs[K] extends { required(this: __gts_rootVmFinalMetaType_29_lhs): true } ? K : never }[keyof __gts_rootVmDefType_27]; }; ((_: __gts_rootVmFinalMetaType_29_rans.Expected extends __gts_rootVmFinalMetaType_29_rans.Collected ? string : __gts_rootVmFinalMetaType_29_rans.Expected) => 0)("__gts_rootVmFinalMetaType_29_rans_NeedleString" as any as "required attributes are missing");;
type __gts_rootVmDefType_47 = (typeof __gts_root_vm)[__gts_namedDef]; type __gts_rootVmInitMetaType_48 = __gts_rootVmDefType_47[__gts_meta];;
type __gts_attr_obj_50_uniqueKey_lhs = { [__gts_meta]: __gts_rootVmInitMetaType_48;  uniqueKey: __gts_rootVmDefType_47 extends { ["summon"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_50_uniqueKey_lhs!: __gts_attr_obj_50_uniqueKey_lhs; let __gts_attr_obj_50_uniqueKey = __gts_attr_obj_50_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_50_uniqueKey = typeof __gts_attr_obj_50_uniqueKey; let __gts_attr_obj_50_uniqueKeyFor___gts_attr_obj_50!: `${__gts_attr_obj_50_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_50`; interface __gts_rootVmDefType_47_uniqueKeyProbeHelper { [__gts_attr_obj_50_uniqueKeyFor___gts_attr_obj_50]: 1; } type __gts_attr_obj_50_omittedKeys = __gts_meta | ( __gts_attr_obj_50_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_rootVmDefType_47_uniqueKeyProbeHelper ? keyof __gts_rootVmDefType_47                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_rootVmDefType_47_uniqueKeyProbeHelper & `${__gts_attr_obj_50_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "summon"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_50!: { [__gts_meta]: __gts_rootVmInitMetaType_48 } & Omit<__gts_rootVmDefType_47, __gts_attr_obj_50_omittedKeys>;;

const __gts_attrRet_51 = __gts_attr_obj_50.summon();

type __gts_nestedVm_52 = __gts_attrRet_51 extends { namedDefinition: infer Def } ? Def : { [__gts_meta]: unknown }; type __gts_nestedVmInitMetaType_53 = __gts_nestedVm_52[__gts_meta];;
type __gts_attr_obj_55_uniqueKey_lhs = { [__gts_meta]: __gts_nestedVmInitMetaType_53;  uniqueKey: __gts_nestedVm_52 extends { ["id"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_55_uniqueKey_lhs!: __gts_attr_obj_55_uniqueKey_lhs; let __gts_attr_obj_55_uniqueKey = __gts_attr_obj_55_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_55_uniqueKey = typeof __gts_attr_obj_55_uniqueKey; let __gts_attr_obj_55_uniqueKeyFor___gts_attr_obj_55!: `${__gts_attr_obj_55_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_55`; interface __gts_nestedVm_52_uniqueKeyProbeHelper { [__gts_attr_obj_55_uniqueKeyFor___gts_attr_obj_55]: 1; } type __gts_attr_obj_55_omittedKeys = __gts_meta | ( __gts_attr_obj_55_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_52_uniqueKeyProbeHelper ? keyof __gts_nestedVm_52                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_52_uniqueKeyProbeHelper & `${__gts_attr_obj_55_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "id"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_55!: { [__gts_meta]: __gts_nestedVmInitMetaType_53 } & Omit<__gts_nestedVm_52, __gts_attr_obj_55_omittedKeys>;;

const __gts_attrRet_56 = __gts_attr_obj_55.id(112011);

type gts_binding_type_2_lhs = { [__gts_meta]: __gts_nestedVmFinalMetaType_54; as: __gts_nestedVm_52 extends { ["id"]: { as: infer As } } ? As : unknown; }; let gts_binding_type_2_lhs!: gts_binding_type_2_lhs; let gts_binding_type_2 = gts_binding_type_2_lhs.as(); type gts_binding_type_2 = typeof gts_binding_type_2;;
type __gts_attrRet_56 = typeof __gts_attrRet_56; type __gts_newMeta__57 = __gts_attrRet_56 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_nestedVmInitMetaType_53;
type __gts_attr_obj_58_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__57;  uniqueKey: __gts_nestedVm_52 extends { ["usage"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_58_uniqueKey_lhs!: __gts_attr_obj_58_uniqueKey_lhs; let __gts_attr_obj_58_uniqueKey = __gts_attr_obj_58_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_58_uniqueKey = typeof __gts_attr_obj_58_uniqueKey; let __gts_attr_obj_58_uniqueKeyFor___gts_attr_obj_58!: `${__gts_attr_obj_58_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_58`; interface __gts_nestedVm_52_uniqueKeyProbeHelper { [__gts_attr_obj_58_uniqueKeyFor___gts_attr_obj_58]: 1; } type __gts_attr_obj_58_omittedKeys = __gts_meta | ( __gts_attr_obj_58_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_52_uniqueKeyProbeHelper ? keyof __gts_nestedVm_52                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_52_uniqueKeyProbeHelper & `${__gts_attr_obj_58_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "usage"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_58!: { [__gts_meta]: __gts_newMeta__57 } & Omit<__gts_nestedVm_52, __gts_attr_obj_58_omittedKeys>;;

const __gts_attrRet_59 = __gts_attr_obj_58.usage(2);

type __gts_nestedVm_60 = __gts_attrRet_59 extends { namedDefinition: infer Def } ? Def : { [__gts_meta]: unknown }; type __gts_nestedVmInitMetaType_61 = __gts_nestedVm_60[__gts_meta];;
type __gts_attr_obj_63_uniqueKey_lhs = { [__gts_meta]: __gts_nestedVmInitMetaType_61;  uniqueKey: __gts_nestedVm_60 extends { ["appendLimit"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_63_uniqueKey_lhs!: __gts_attr_obj_63_uniqueKey_lhs; let __gts_attr_obj_63_uniqueKey = __gts_attr_obj_63_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_63_uniqueKey = typeof __gts_attr_obj_63_uniqueKey; let __gts_attr_obj_63_uniqueKeyFor___gts_attr_obj_63!: `${__gts_attr_obj_63_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_63`; interface __gts_nestedVm_60_uniqueKeyProbeHelper { [__gts_attr_obj_63_uniqueKeyFor___gts_attr_obj_63]: 1; } type __gts_attr_obj_63_omittedKeys = __gts_meta | ( __gts_attr_obj_63_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_60_uniqueKeyProbeHelper ? keyof __gts_nestedVm_60                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_60_uniqueKeyProbeHelper & `${__gts_attr_obj_63_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "appendLimit"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_63!: { [__gts_meta]: __gts_nestedVmInitMetaType_61 } & Omit<__gts_nestedVm_60, __gts_attr_obj_63_omittedKeys>;;

const __gts_attrRet_64 = __gts_attr_obj_63.appendLimit(6);

type __gts_attrRet_64 = typeof __gts_attrRet_64; type __gts_newMeta__65 = __gts_attrRet_64 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_nestedVmInitMetaType_61;
type __gts_attr_obj_66_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__65;  uniqueKey: __gts_nestedVm_60 extends { ["appendCount"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_66_uniqueKey_lhs!: __gts_attr_obj_66_uniqueKey_lhs; let __gts_attr_obj_66_uniqueKey = __gts_attr_obj_66_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_66_uniqueKey = typeof __gts_attr_obj_66_uniqueKey; let __gts_attr_obj_66_uniqueKeyFor___gts_attr_obj_66!: `${__gts_attr_obj_66_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_66`; interface __gts_nestedVm_60_uniqueKeyProbeHelper { [__gts_attr_obj_66_uniqueKeyFor___gts_attr_obj_66]: 1; } type __gts_attr_obj_66_omittedKeys = __gts_meta | ( __gts_attr_obj_66_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_60_uniqueKeyProbeHelper ? keyof __gts_nestedVm_60                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_60_uniqueKeyProbeHelper & `${__gts_attr_obj_66_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "appendCount"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_66!: { [__gts_meta]: __gts_newMeta__65 } & Omit<__gts_nestedVm_60, __gts_attr_obj_66_omittedKeys>;;

const __gts_attrRet_67 = __gts_attr_obj_66.appendCount(1);

type __gts_attrRet_67 = typeof __gts_attrRet_67; type __gts_newMeta__68 = __gts_attrRet_67 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__65;
type __gts_nestedVmFinalMetaType_62 = __gts_newMeta__68; let __gts_nestedVmFinalMetaType_62_lhs!: { [__gts_meta]: __gts_newMeta__68 } & Omit<__gts_nestedVm_60, __gts_meta>; type __gts_nestedVmFinalMetaType_62_lhs = typeof __gts_nestedVmFinalMetaType_62_lhs; namespace __gts_nestedVmFinalMetaType_62_rans { export type Collected = "appendLimit" | "appendCount"; export type Expected = { [K in keyof __gts_nestedVm_60]: __gts_nestedVmFinalMetaType_62_lhs[K] extends { required(this: __gts_nestedVmFinalMetaType_62_lhs): true } ? K : never }[keyof __gts_nestedVm_60]; }; ((_: __gts_nestedVmFinalMetaType_62_rans.Expected extends __gts_nestedVmFinalMetaType_62_rans.Collected ? string : __gts_nestedVmFinalMetaType_62_rans.Expected) => 0)("__gts_nestedVmFinalMetaType_62_rans_NeedleString" as any as "required attributes are missing");;
type __gts_attrRet_59 = typeof __gts_attrRet_59; type __gts_newMeta__69 = __gts_attrRet_59 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__57;
type __gts_attr_obj_70_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__69;  uniqueKey: __gts_nestedVm_52 extends { ["on"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_70_uniqueKey_lhs!: __gts_attr_obj_70_uniqueKey_lhs; let __gts_attr_obj_70_uniqueKey = __gts_attr_obj_70_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_70_uniqueKey = typeof __gts_attr_obj_70_uniqueKey; let __gts_attr_obj_70_uniqueKeyFor___gts_attr_obj_70!: `${__gts_attr_obj_70_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_70`; interface __gts_nestedVm_52_uniqueKeyProbeHelper { [__gts_attr_obj_70_uniqueKeyFor___gts_attr_obj_70]: 1; } type __gts_attr_obj_70_omittedKeys = __gts_meta | ( __gts_attr_obj_70_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_52_uniqueKeyProbeHelper ? keyof __gts_nestedVm_52                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_52_uniqueKeyProbeHelper & `${__gts_attr_obj_70_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "on"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_70!: { [__gts_meta]: __gts_newMeta__69 } & Omit<__gts_nestedVm_52, __gts_attr_obj_70_omittedKeys>;;

const __gts_attrRet_71 = __gts_attr_obj_70.on('endPhase');

type __gts_nestedVm_72 = __gts_attrRet_71 extends { namedDefinition: infer Def } ? Def : { [__gts_meta]: unknown }; type __gts_nestedVmInitMetaType_73 = __gts_nestedVm_72[__gts_meta];;
type __gts_attr_obj_75_uniqueKey_lhs = { [__gts_meta]: __gts_nestedVmInitMetaType_73;  uniqueKey: __gts_nestedVm_72 extends { ["when"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_75_uniqueKey_lhs!: __gts_attr_obj_75_uniqueKey_lhs; let __gts_attr_obj_75_uniqueKey = __gts_attr_obj_75_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_75_uniqueKey = typeof __gts_attr_obj_75_uniqueKey; let __gts_attr_obj_75_uniqueKeyFor___gts_attr_obj_75!: `${__gts_attr_obj_75_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_75`; interface __gts_nestedVm_72_uniqueKeyProbeHelper { [__gts_attr_obj_75_uniqueKeyFor___gts_attr_obj_75]: 1; } type __gts_attr_obj_75_omittedKeys = __gts_meta | ( __gts_attr_obj_75_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_72_uniqueKeyProbeHelper ? keyof __gts_nestedVm_72                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_72_uniqueKeyProbeHelper & `${__gts_attr_obj_75_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "when"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_75!: { [__gts_meta]: __gts_nestedVmInitMetaType_73 } & Omit<__gts_nestedVm_72, __gts_attr_obj_75_omittedKeys>;;

const __gts_attrRet_76 = __gts_attr_obj_75.when((
  __gts_fnArg,
  { cryo, hydro, pyro, electro, anemo, geo, dendro, omni } = __gts_fnArg[__gts_Prelude]
) => true);

type __gts_attrRet_76 = typeof __gts_attrRet_76; type __gts_newMeta__77 = __gts_attrRet_76 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_nestedVmInitMetaType_73;
type __gts_attr_obj_78_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__77;  uniqueKey: __gts_nestedVm_72 extends { ["hint"]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_78_uniqueKey_lhs!: __gts_attr_obj_78_uniqueKey_lhs; let __gts_attr_obj_78_uniqueKey = __gts_attr_obj_78_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_78_uniqueKey = typeof __gts_attr_obj_78_uniqueKey; let __gts_attr_obj_78_uniqueKeyFor___gts_attr_obj_78!: `${__gts_attr_obj_78_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_78`; interface __gts_nestedVm_72_uniqueKeyProbeHelper { [__gts_attr_obj_78_uniqueKeyFor___gts_attr_obj_78]: 1; } type __gts_attr_obj_78_omittedKeys = __gts_meta | ( __gts_attr_obj_78_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_72_uniqueKeyProbeHelper ? keyof __gts_nestedVm_72                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_72_uniqueKeyProbeHelper & `${__gts_attr_obj_78_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? "hint"                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_78!: { [__gts_meta]: __gts_newMeta__77 } & Omit<__gts_nestedVm_72, __gts_attr_obj_78_omittedKeys>;;

const __gts_attrRet_79 = __gts_attr_obj_78.hint('heal', 1);

type __gts_attrRet_79 = typeof __gts_attrRet_79; type __gts_newMeta__80 = __gts_attrRet_79 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__77;
type __gts_attr_obj_81_uniqueKey_lhs = { [__gts_meta]: __gts_newMeta__80;  uniqueKey: __gts_nestedVm_72 extends { [__gts_Action]: { uniqueKey: infer UniqueKey } } ? UniqueKey : () => 0; }; let __gts_attr_obj_81_uniqueKey_lhs!: __gts_attr_obj_81_uniqueKey_lhs; let __gts_attr_obj_81_uniqueKey = __gts_attr_obj_81_uniqueKey_lhs.uniqueKey(); type __gts_attr_obj_81_uniqueKey = typeof __gts_attr_obj_81_uniqueKey; let __gts_attr_obj_81_uniqueKeyFor___gts_attr_obj_81!: `${__gts_attr_obj_81_uniqueKey}${__gts_util.UniqueKeyProbSegment}__gts_attr_obj_81`; interface __gts_nestedVm_72_uniqueKeyProbeHelper { [__gts_attr_obj_81_uniqueKeyFor___gts_attr_obj_81]: 1; } type __gts_attr_obj_81_omittedKeys = __gts_meta | ( __gts_attr_obj_81_uniqueKey extends 0 ? never                                                 /* no unique requirement */ : string extends keyof __gts_nestedVm_72_uniqueKeyProbeHelper ? keyof __gts_nestedVm_72                          /* too loose, disable all */ : __gts_util.UnionToIntersection< keyof __gts_nestedVm_72_uniqueKeyProbeHelper & `${__gts_attr_obj_81_uniqueKey}${__gts_util.UniqueKeyProbSegment}${string}` > extends never ? __gts_Action                             /* have duplicate, disable this */ : never ); let __gts_attr_obj_81!: { [__gts_meta]: __gts_newMeta__80 } & Omit<__gts_nestedVm_72, __gts_attr_obj_81_omittedKeys>;;

const __gts_attrRet_82 = __gts_attr_obj_81[__gts_Action]((
  __gts_fnArg,
  { cryo, hydro, pyro, electro, anemo, geo, dendro, omni } = __gts_fnArg[__gts_Prelude]
) => {
  __gts_fnArg.heal(1, __gts_query(({ my, opp }) => my.character, { star: true }));

  const currentUsage = __gts_fnArg.getVariable("usage");

  __gts_fnArg.apply(hydro, __gts_query(({ my, opp }) => my.active, { star: false }));
});

type __gts_nestedVmFinalMetaType_74 = __gts_newMeta__80; let __gts_nestedVmFinalMetaType_74_lhs!: { [__gts_meta]: __gts_newMeta__80 } & Omit<__gts_nestedVm_72, __gts_meta>; type __gts_nestedVmFinalMetaType_74_lhs = typeof __gts_nestedVmFinalMetaType_74_lhs; namespace __gts_nestedVmFinalMetaType_74_rans { export type Collected = "when" | "hint" | __gts_Action; export type Expected = { [K in keyof __gts_nestedVm_72]: __gts_nestedVmFinalMetaType_74_lhs[K] extends { required(this: __gts_nestedVmFinalMetaType_74_lhs): true } ? K : never }[keyof __gts_nestedVm_72]; }; ((_: __gts_nestedVmFinalMetaType_74_rans.Expected extends __gts_nestedVmFinalMetaType_74_rans.Collected ? string : __gts_nestedVmFinalMetaType_74_rans.Expected) => 0)("__gts_nestedVmFinalMetaType_74_rans_NeedleString" as any as "required attributes are missing");;
type __gts_attrRet_71 = typeof __gts_attrRet_71; type __gts_newMeta__83 = __gts_attrRet_71 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_newMeta__69;
type __gts_nestedVmFinalMetaType_54 = __gts_newMeta__83; let __gts_nestedVmFinalMetaType_54_lhs!: { [__gts_meta]: __gts_newMeta__83 } & Omit<__gts_nestedVm_52, __gts_meta>; type __gts_nestedVmFinalMetaType_54_lhs = typeof __gts_nestedVmFinalMetaType_54_lhs; namespace __gts_nestedVmFinalMetaType_54_rans { export type Collected = "id" | "usage" | "on"; export type Expected = { [K in keyof __gts_nestedVm_52]: __gts_nestedVmFinalMetaType_54_lhs[K] extends { required(this: __gts_nestedVmFinalMetaType_54_lhs): true } ? K : never }[keyof __gts_nestedVm_52]; }; ((_: __gts_nestedVmFinalMetaType_54_rans.Expected extends __gts_nestedVmFinalMetaType_54_rans.Collected ? string : __gts_nestedVmFinalMetaType_54_rans.Expected) => 0)("__gts_nestedVmFinalMetaType_54_rans_NeedleString" as any as "required attributes are missing");;
type __gts_attrRet_51 = typeof __gts_attrRet_51; type __gts_newMeta__84 = __gts_attrRet_51 extends { rewriteMeta: infer NewMeta extends {} } ? NewMeta : __gts_rootVmInitMetaType_48;
type __gts_rootVmFinalMetaType_49 = __gts_newMeta__84; let __gts_rootVmFinalMetaType_49_lhs!: { [__gts_meta]: __gts_newMeta__84 } & Omit<__gts_rootVmDefType_47, __gts_meta>; type __gts_rootVmFinalMetaType_49_lhs = typeof __gts_rootVmFinalMetaType_49_lhs; namespace __gts_rootVmFinalMetaType_49_rans { export type Collected = "summon"; export type Expected = { [K in keyof __gts_rootVmDefType_47]: __gts_rootVmFinalMetaType_49_lhs[K] extends { required(this: __gts_rootVmFinalMetaType_49_lhs): true } ? K : never }[keyof __gts_rootVmDefType_47]; }; ((_: __gts_rootVmFinalMetaType_49_rans.Expected extends __gts_rootVmFinalMetaType_49_rans.Collected ? string : __gts_rootVmFinalMetaType_49_rans.Expected) => 0)("__gts_rootVmFinalMetaType_49_rans_NeedleString" as any as "required attributes are missing");;

const sub = (a: number, b: number) => {
  return a - b;
};

export const obj = { foo: "bar", sub: (name: string) => {} }; // obj.sub("test");

// (0, obj).sub("test");
obj.foo ? 'a' : 'b';

new Date();
