export const specialIdentifiers = [
  // Always Reserved Words
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  // Strict Mode Reserved Words
  "let",
  "static",
  "yield",
  "await",
  // Future Reserved Words
  "enum",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  // Contextual Keywords (Identifier with special meaning in specific context)
  "as",
  "async",
  "from",
  "get",
  "of",
  "set",
  // TypeScript Keywords (Only taken from https://github.com/tc39/proposal-type-annotations)
  "type",
  // Our DSL Keywords
  "define",
  "query",
];
